#Bai1

In [1]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#Bai2

In [2]:
import torch
torch.manual_seed(42)
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)


tensor([[0.6346, 0.8309, 0.3244, 0.7474],
        [0.4487, 0.8882, 0.1880, 0.3907],
        [0.4491, 0.2890, 0.0703, 0.8101]])
tensor([[ 1.1294,  1.3401,  1.2053, -0.8967],
        [ 1.3321, -0.3605,  1.3642, -0.7451],
        [ 3.0193,  0.3422,  1.1556,  1.8786]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [6]:
import torch
f = torch.full((5,5),10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


#Bai3

In [7]:
import torch
a= torch.zeros(2,3,4)
print("Tensor:")
print(a)
print("Shape:",a.shape)
print("Size:",a.size())
print("Number of dimensions:",a.ndim)
print("Data type:",a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


#Bài4


In [16]:
import torch
torch.manual_seed(42)
a = torch.randn(3,4,5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:,2:4])

print("Shape of a[1]:")
print(a[1].shape)

print("Shape of a[1:,2:4]:")
print(a[1:,2:4].shape)

print("2 last elements of Tensor:")
print(a[:,:,-2:])

Original tensor:
tensor([[[ 1.1237,  0.2527, -0.0041,  0.2237,  0.8632],
         [ 1.0812, -0.4300,  1.3390,  0.5965, -0.5331],
         [-1.0369, -1.7769,  0.3189,  0.1111,  1.4051],
         [ 0.4031,  0.1315, -0.2692,  1.3746,  0.6614]],

        [[ 0.0484,  0.6153,  0.0169,  1.4482, -1.0215],
         [-1.3890,  1.5204, -0.7864,  1.8245, -0.9200],
         [-1.0201, -0.6575, -0.5677, -0.3360, -1.1779],
         [-2.1820, -0.2088,  1.6419, -0.6066, -0.7538]],

        [[ 0.5883, -1.4862,  1.6397,  0.8703,  0.5505],
         [-0.0349,  0.5095, -0.2824, -0.3836,  1.3484],
         [ 0.9304, -1.3590,  0.2739,  0.4489,  0.4833],
         [-0.1538,  1.0427,  0.1511,  1.5099, -1.3628]]])

Tensor a[1]:
tensor([[ 0.0484,  0.6153,  0.0169,  1.4482, -1.0215],
        [-1.3890,  1.5204, -0.7864,  1.8245, -0.9200],
        [-1.0201, -0.6575, -0.5677, -0.3360, -1.1779],
        [-2.1820, -0.2088,  1.6419, -0.6066, -0.7538]])

Tensor a[1:, 2:4]:
tensor([[[-1.0201, -0.6575, -0.5677, -0.3360, -1.1

#Bài5

In [18]:
import torch
torch.manual_seed(42)
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))
print(a.reshape(2,6))

Original:
tensor([[ 1.3140, -0.3380, -0.1648, -0.1636],
        [-1.2504,  1.5930, -0.7188,  0.8857],
        [-0.6463,  0.3045,  0.6610,  0.2418]])

Flatten:
tensor([ 1.3140, -0.3380, -0.1648, -0.1636, -1.2504,  1.5930, -0.7188,  0.8857,
        -0.6463,  0.3045,  0.6610,  0.2418])

Reshape to 3 x 2 x 2:
tensor([[[ 1.3140, -0.3380],
         [-0.1648, -0.1636]],

        [[-1.2504,  1.5930],
         [-0.7188,  0.8857]],

        [[-0.6463,  0.3045],
         [ 0.6610,  0.2418]]])
tensor([[ 1.3140, -0.3380, -0.1648, -0.1636, -1.2504,  1.5930],
        [-0.7188,  0.8857, -0.6463,  0.3045,  0.6610,  0.2418]])


#Bài6

In [26]:
import torch
torch.manual_seed(42)
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)
print("Shape of a @ b.T")
c = a @ b.T
print(c.shape)

a:
tensor([[ 0.1360,  0.6107, -0.5926],
        [-0.4806,  1.0003, -1.1989]])
b:
tensor([[ 0.5943,  0.8130, -0.1148],
        [-0.5338,  1.3977,  0.0247]])

a + b:
tensor([[ 0.7303,  1.4237, -0.7073],
        [-1.0144,  2.3980, -1.1742]])

a / b:
tensor([[  0.2288,   0.7512,   5.1636],
        [  0.9003,   0.7157, -48.4907]])

a^2:
tensor([[0.0185, 0.3730, 0.3512],
        [0.2310, 1.0006, 1.4374]])

Matrix multiplication:
tensor([[0.6453, 0.7664],
        [0.6652, 1.6251]])
Shape of a @ b.T
torch.Size([2, 2])


#Bài7

In [31]:
import torch
torch.manual_seed(42)
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print("\n")
print(torch.cumsum(a, dim=0))


tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

Mean:
tensor([-0.1082,  0.0699,  0.9925,  0.1339])

Standard deviation:
tensor([0.8810, 0.2325, 1.0635, 0.7285])

Cumulative sum:


tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-0.7862, -0.0575,  2.4427, -0.4077],
        [-0.3245,  0.2098,  2.9776,  0.4017]])


In [33]:
import torch
torch.manual_seed(42)
a = torch.randn(3,4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print("\n")
print(torch.cumsum(a, dim=1))


tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

Mean:
tensor([0.2326, 0.0653, 0.5183])

Standard deviation:
tensor([0.0849, 1.4789, 0.2245])

Cumulative sum:


tensor([[ 0.3367,  0.4655,  0.7000,  0.9303],
        [-1.1229, -1.3092,  0.8990,  0.2610],
        [ 0.4617,  0.7290,  1.2639,  2.0733]])


#Bài8


In [34]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [40]:

def f(x):
    return x**2
def derivative(x,delta_x):
  return (f(x + delta_x)-f(x))/delta_x
  pass
x = 3.6
delta_x=1e-5
result = derivative(x,delta_x=1e-5)
print(f'Derivative of x^2 at x = 3.6 is : {result}')


Derivative of x^2 at x = 3.6 is : 7.200009999941414


In [44]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = 3*x*x + 2*x + 1
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


#Bài9

In [84]:
import numpy as np
import torch

np.random.seed(42)
torch.manual_seed(42)

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.3367],
        [0.1288],
        [0.2345]], requires_grad=True)
Learned coefficients:
tensor([[1.0087],
        [2.0033],
        [2.5330]], requires_grad=True)


#Bài10

In [94]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
  y1 = A + B - 9
  y2 = C - D - 1
  y3 = A + C - 8
  y4 = B - D - 2
  sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
  optimizer.zero_grad()
  sqerr.backward()
  optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.3676, requires_grad=True)
B = tensor(4.6324, requires_grad=True)
C = tensor(3.6324, requires_grad=True)
D = tensor(2.6324, requires_grad=True)


#Bài11

##Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

In [92]:
import torch
import numpy
X = torch.arange(24)
print(X)
print(X.shape)
X=X.reshape(4,6)
print("\n4x6:")
print(f'\n{X.shape}')
X=X.reshape(2,12)
print("\n2x12:")
print(f'\n{X.shape}')
X=X.reshape(2,3,4)
print("\n2x3x4:")
print(f'\n{X.shape}')



tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
torch.Size([24])

4x6:

torch.Size([4, 6])

2x12:

torch.Size([2, 12])

2x3x4:

torch.Size([2, 3, 4])


##Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

In [98]:
import torch
torch.manual_seed(42)
A = torch.rand(3,4)
B = torch.rand(3,4)
print(A)
print(B)
add_Tensor = A+B
mul_Tensor = A*B
div_Tensor = A/B
meanA = torch.mean(A,dim=0)
meanB = torch.mean(B,dim=0)
stdDevA = torch.std(A,dim=0)
stdDevB = torch.std(B,dim=0)
print("A+B:")
print(add_Tensor)
print("A*B:")
print(mul_Tensor)
print("A/B:")
print(div_Tensor)
print("mean A:")
print(meanA)
print("mean B:")
print(meanB)
print("std Dev A:")
print(stdDevA)
print("std Dev B:")
print(stdDevB)




tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
A+B:
tensor([[1.7517, 1.4827, 1.1240, 1.3887],
        [1.2759, 1.1748, 0.5232, 1.4211],
        [1.2104, 0.5745, 1.2315, 1.4253]])
A*B:
tensor([[0.7670, 0.5195, 0.2837, 0.4119],
        [0.3457, 0.3449, 0.0684, 0.4980],
        [0.2537, 0.0588, 0.2775, 0.4937]])
A/B:
tensor([[1.0148, 1.6117, 0.5166, 2.2340],
        [0.4410, 1.0470, 0.9625, 1.2649],
        [3.4891, 0.3018, 3.1476, 0.7137]])
mean A:
tensor([0.7378, 0.5497, 0.5247, 0.7822])
mean B:
tensor([0.6748, 0.5277, 0.4349, 0.6295])
std Dev A:
tensor([0.3023, 0.3934, 0.3606, 0.1831])
std Dev B:
tensor([0.3510, 0.0748, 0.2656, 0.2011])


##Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

In [102]:
import torch
x = torch.tensor(2.0,requires_grad=True)
y = 2*x*x + 5*x + 3
y.backward()
print("x=", x)
print("y=",y)
print("x.grad =",x.grad)

def f(x):
  return 2*x**2 +5*x + 3
def derivative(x,delta_x=1e-5):
  return (f(x+delta_x)-f(x))/delta_x
X = 2
print("x= ",X)
print("derivative of 2*x^2 + 5*x + 3 at x = 2 is: ")
print(derivative(X))



x= tensor(2., requires_grad=True)
y= tensor(21., grad_fn=<AddBackward0>)
x.grad = tensor(13.)
x=  2
derivative of 2*x^2 + 5*x + 3 at x = 2 is: 
13.000020000220045


##Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [103]:
import numpy as np
import torch

np.random.seed(42)
torch.manual_seed(42)

polynomial = np.poly1d([2, -3, 5])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(5000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.3367],
        [0.1288],
        [0.2345]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0000],
        [-3.0000],
        [ 4.9997]], requires_grad=True)
